apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stoat.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  Revolt.toml: |
    # Reference: https://github.com/stoatchat/stoatchat/blob/stable/crates/core/config/Revolt.toml
    # WARNING: This file is managed by Helm. Changes will be overwritten next time the chart is updated.
    production = {{ .Values.stoat.config.production }}

    [database]
    mongodb = {{ .Values.global.subcharts.mongo.connection_url | default (printf "mongodb://%s-mongodb" .Release.Name) | quote }}
    redis = {{ .Values.global.subcharts.redis.connection_url | default (printf "redis://%s-redis-master" .Release.Name) | quote }}

    [rabbit]
    host = {{ .Values.global.subcharts.rabbitmq.host | default (printf "%s-rabbitmq" .Release.Name) | quote }}
    port = {{ .Values.global.subcharts.rabbitmq.port }}
    username = {{ .Values.global.subcharts.rabbitmq.username | quote }}
    password = {{ .Values.global.subcharts.rabbitmq.password | quote }}

    [hosts]
    app = "https://{{ .Values.global.domain }}"
    api = "https://{{ .Values.global.domain }}/api"
    events = "wss://{{ .Values.global.domain }}/ws"
    autumn = "https://{{ .Values.global.domain }}/autumn"
    january = "https://{{ .Values.global.domain }}/january"

    [pushd.vapid]
    private_key = {{ .Values.global.secret.vapid_key | quote }}
    public_key = {{ .Values.global.secret.vapid_public_key | quote }}

    [files]
    encryption_key = {{ .Values.global.secret.encryption_key | quote }}

    [files.s3]
    endpoint = {{ .Values.global.subcharts.minio.connection_url | default (printf "http://%s-minio:9000" .Release.Name) | quote }}
    region = {{ .Values.stoat.config.files.s3.region | quote }}
    default_bucket = {{ .Values.stoat.config.files.s3.default_bucket | quote }}
    access_key_id = {{ .Values.stoat.config.files.s3.access_key_id | quote }}
    secret_access_key = {{ .Values.stoat.config.files.s3.secret_access_key | quote }}
    path_style_buckets = {{ .Values.stoat.config.files.s3.path_style_buckets }}

    [api]

    [api.registration]
    invite_only = {{ .Values.stoat.config.api.registration.invite_only }}

    [api.smtp]
    host = {{ .Values.stoat.config.api.smtp.host | quote }}
    port = {{ .Values.stoat.config.api.smtp.port | quote }}
    username = {{ .Values.stoat.config.api.smtp.username | quote }}
    password = {{ .Values.stoat.config.api.smtp.password | quote }}
    from_address = {{ .Values.stoat.config.api.smtp.from_address | quote }}
    reply_to = {{ .Values.stoat.config.api.smtp.reply_to | quote }}
    use_tls = {{ .Values.stoat.config.api.smtp.use_tls | quote }}

{{- /* TODO: Support more config options */ -}}
